/*
   哇咔咔, 我是文件头!!!
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

// MyCrdListerExpansion allows custom methods to be added to
// MyCrdLister.
type MyCrdListerExpansion interface{}

// MyCrdNamespaceListerExpansion allows custom methods to be added to
// MyCrdNamespaceLister.
type MyCrdNamespaceListerExpansion interface{}
