---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kube-system-default-admin
  labels:
    app: ingress-nginx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  ## 将 kube-system 下的 default 用户绑定到 cluster-admin 角色, 拥有超级权限.
  name: default
  namespace: kube-system

---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-svc
  namespace: kube-system
spec:
  selector:
    app: ingress-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30080
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
      nodePort: 30443
  type: NodePort
