/*
   哇咔咔, 我是文件头!!!
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "mycrd/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// MyCrds returns a MyCrdInformer.
	MyCrds() MyCrdInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// MyCrds returns a MyCrdInformer.
func (v *version) MyCrds() MyCrdInformer {
	return &myCrdInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
