apiVersion: kubeadm.k8s.io/v1beta2
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: q8fszx.6razfduu22ouz4x2
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.80.121
  bindPort: 6443
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  name: k8s-master-01
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.17.2
clusterName: kubernetes
imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers
apiServer:
  timeoutForControlPlane: 4m0s
  extraArgs:
    enable-admission-plugins: NodeRestriction
    authorization-mode: "Node,RBAC"
    endpoint-reconciler-type: lease
  ## kubectl 所用的 kubeconfig 中, cluster.server 的地址必须是该列表中的其中一个才能够访问.
  ## 比如, 在阿里云上创建 kube 集群, 公网IP是会变化的, controlPlaneEndpoint 只能写内网地址,
  ## 但是在本地开发时, kubeconfig 中如果写公网IP是无法访问集群的, 会被拒绝. 
  ## 因此这里最好设置一个域名, 本地将该域名与公网IP写入 hosts, IP变化就无法影响了.
  ## 默认一定会包含 control plane 的 hostname 值.
  certSANs:
  - kubernetes
  - k8s-master-01
  - ${eth0_IP}
certificatesDir: /etc/kubernetes/pki
controlPlaneEndpoint: k8s-server-lb:8443
featureGates:
  IPv6DualStack: true
controllerManager:
  extraArgs:
    cluster-cidr: 10.254.0.0/16,fec0:20::/96
    service-cluster-ip-range: 10.96.0.0/12,fec0:30::/112
    ## node-cidr-mask-size 掩码位要比上面的 cluster-cidr 大, 否则升级/部署完成后 controller-manager 会经常崩溃重启.
    ## Controller: Invalid --cluster-cidr, mask size of cluster CIDR must be less than or equal to --node-cidr-mask-size configured for CIDR family
    ## 具体含义有待商讨. 注意是字符串类型
    ## node-cidr-mask-size: "112"
    ## ...又错, 双栈场景下  node-cidr-mask-size 字段被禁用, controller-manager 启动直接失败, 需要使用 node-cidr-mask-size-ipv6.
    ## error starting controllers: usage of --node-cidr-mask-size is not allowed with dual-stack clusters
    node-cidr-mask-size-ipv6: "112"
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
networking:
  dnsDomain: cluster.local
  ## 不知道是不是 kubeadm 还是 apiserver 的限制, serviceSubnet 的掩码位小于 96 都会出错:
  ## specified --secondary-service-cluster-ip-range is too large.
  ## 目前来说, 112 是比较合适的.
  podSubnet: 10.254.0.0/16,fec0:20::/96
  serviceSubnet: 10.96.0.0/12,fec0:30::/112
scheduler: {}
