## 使用方法
## k create ns monitoring
## helm install prometheus -n monitoring -f /home/charts/stable.prometheus.yaml stable/prometheus
## helm upgrade prometheus -n monitoring -f /home/charts/stable.prometheus.yaml stable/prometheus

server:
  enabled: true
  name: server
  enableAdminApi: false

  global:
    scrape_interval: 1m
    scrape_timeout: 10s
    ## How frequently to evaluate rules
    evaluation_interval: 1m

  replicaCount: 1
  statefulSet:
    ## 如果是false则使用deployment部署, 否则用statefulSet部署.
    enabled: false
    ## Alertmanager headless service to use for the statefulset
    headless:
      servicePort: 80

  service:
    type: NodePort
    servicePort: 80
    nodePort: 30090
  ingress:
    enabled: false
    hosts: []
    #   - alertmanager.domain.com
    #   - domain.com/alertmanager
    tls: []
    #   - secretName: prometheus-alerts-tls
    #     hosts:
    #       - alertmanager.domain.com
  persistentVolume:
    enabled: true
    storageClass: local-path

## server end ...

alertmanager:
  enabled: true
  replicaCount: 1
  ingress:
    enabled: false

  service:
    type: NodePort
    servicePort: 80
    nodePort: 30180

  persistentVolume:
    ## false会使用emptyDir
    enabled: true
    storageClass: local-path

## alertmanager end ...

kubeStateMetrics:
  enabled: true
  name: kube-state-metrics
  replicaCount: 1
  service:
    type: ClusterIP
    servicePort: 80
## kubeStateMetrics end ...

nodeExporter:
  enabled: true
  name: node-exporter
  hostNetwork: true
  hostPID: true

  service:
    type: ClusterIP
    hostPort: 9100
    servicePort: 9100
## nodeExporter end ...

pushgateway:
  enabled: true
  name: pushgateway
  replicaCount: 1
  service:
    type: ClusterIP
    servicePort: 9091
  ingress:
    enabled: false
  persistentVolume:
    enabled: false
## pushgateway end ...

serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
            - localhost:9090
      ## job prometheus end ...
      - job_name: kubernetes-apiservers
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names: 
                - default
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: default;kubernetes;https

      ## job kubernetes-apiservers end 

## serverFiles end ...
