groups:
  - name: deploy-pod.rules
    rules:
      - alert: kube_statefulset_replicas_unavailable
        expr: kube_statefulset_status_replicas < kube_statefulset_replicas
        for: 5m
        labels:
          severity: Warning
        annotations:
          description: 'statefulset {{$labels.statefulset}} has {{$value}} replicas, which is less than desired'
          summary: '{{$labels.statefulset}}: has inssuficient replicas.'
      - alert: daemonsets_misscheduled
        expr: kube_daemonset_status_number_misscheduled > 0
        for: 3m
        labels:
          severity: Warning
        annotations:
          description: 'Daemonset {{$labels.daemonset}} is running where it is not supposed to run'
          summary: 'Daemonsets not scheduled correctly'
      - alert: daemonsets_not_scheduled
        expr: kube_daemonset_status_desired_number_scheduled - kube_daemonset_status_current_number_scheduled > 0
        for: 3m
        labels:
          severity: Warning
        annotations:
          description: '{{ $value }} of Daemonset {{$labels.daemonset}} scheduled which is less than desired number'
          summary: 'Less than desired number of daemonsets scheduled'
      - alert: deployment_replicas_unavailable
        expr: kube_deployment_status_replicas_unavailable{deployment!~"default-http-backend-tbj-.*|nginx-ingress-controller-tbj-.*"} > 0
        for: 3m
        labels:
          severity: Warning
        annotations:
          description: 'deployment {{$labels.deployment}} has {{$value}} replicas unavailable'
          summary: '{{$labels.deployment}}: has inssuficient replicas.'
      - alert: deployment_generation_mismatch
        expr: kube_deployment_status_observed_generation{job="kube-state-metrics"} != kube_deployment_metadata_generation{job="kube-state-metrics"}
        for: 5m
        labels:
          severity: High
        annotations:
          message: "Deployment generation for {{ $labels.namespace }}/{{ $labels.deployment}} does not match, this indicates that the Deployment has failed but has not been rolled back."
      - alert: KubeDaemonSetNotScheduled
        expr: kube_daemonset_status_desired_number_scheduled{job="kube-state-metrics"}
          - kube_daemonset_status_current_number_scheduled{job="kube-state-metrics"}
          > 0
        for: 5m
        labels:
          severity: Warning
        annotations:
          message: '{{ $value }} Pods of DaemonSet {{ $labels.namespace }}/{{ $labels.daemonset }} are not scheduled.'
