---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
spec:
  accessModes:
  ## 只接受ReadWriteOnce模式, ReadWriteMany会无法创建PV.
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path