---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-pv-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-pv-pod
  template:
    metadata:
      labels:
        app: local-pv-pod
    spec:
      volumes:
        - name: data-vol
          persistentVolumeClaim:
            claimName: local-pvc
      containers:
      - name: centos7
        image: registry.cn-hangzhou.aliyuncs.com/generals-space/centos:7
        imagePullPolicy: IfNotPresent
        command: ["tail", "-f", "/etc/profile"]
        volumeMounts:
        - name: data-vol
          mountPath: /data
