/*
   哇咔咔, 我是文件头!!!
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	mycrdgroupv1 "mycrd/pkg/apis/mycrdgroup/v1"
	versioned "mycrd/pkg/client/clientset/versioned"
	internalinterfaces "mycrd/pkg/client/informers/externalversions/internalinterfaces"
	v1 "mycrd/pkg/client/listers/mycrdgroup/v1"
	time "time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MyCrdInformer provides access to a shared informer and lister for
// MyCrds.
type MyCrdInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.MyCrdLister
}

type myCrdInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMyCrdInformer constructs a new informer for MyCrd type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMyCrdInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMyCrdInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMyCrdInformer constructs a new informer for MyCrd type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMyCrdInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MycrdgroupV1().MyCrds(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MycrdgroupV1().MyCrds(namespace).Watch(options)
			},
		},
		&mycrdgroupv1.MyCrd{},
		resyncPeriod,
		indexers,
	)
}

func (f *myCrdInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMyCrdInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *myCrdInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&mycrdgroupv1.MyCrd{}, f.defaultInformer)
}

func (f *myCrdInformer) Lister() v1.MyCrdLister {
	return v1.NewMyCrdLister(f.Informer().GetIndexer())
}
