---
apiVersion: v1
kind: Pod
metadata:
  name: calicoctl
  namespace: kube-system
spec:
  nodeSelector:
    beta.kubernetes.io/os: linux
  hostNetwork: true
  ## 官方部署文件缺少hostPID, 结果找不到calico进程
  hostPID: true
  serviceAccountName: calicoctl
  volumes:
    - name: vol-bird
      hostPath:
        path: /var/run/calico
        type: DirectoryOrCreate
  containers:
    - name: calicoctl
      image: calico/ctl:v3.10.1
      command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
      env:
        - name: DATASTORE_TYPE
          value: kubernetes
      volumeMounts:
        - name: vol-bird
          ## 挂载bird目录
          mountPath: /var/run/bird
