apiVersion: v1
clusters:
- cluster:
    certificate-authority: /etc/kubernetes/pki/ca.crt
    server: https://kube-apiserver.generals.space:6443
  name: main
contexts:
- context:
    cluster: main
    namespace: default
    user: main-admin
  name: def
- context:
    cluster: main
    namespace: kube-system
    user: main-admin
  name: sys
current-context: def
kind: Config
preferences: {}
users:
- name: main-admin
  user:
    client-certificate: /etc/kubernetes/pki/
    client-key: /etc/kubernetes/pki/
