apiVersion: v1
kind: Namespace
metadata:
  name: general-test

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pod
  labels:
    app: nginx-pod
  namespace: general-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx-svc
  namespace: general-test
spec:
  ports:
    - port: 80
      name: http
      targetPort: 80
      nodePort: 30080
  selector:
    app: nginx-pod
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ing
  labels:
    app: nginx-ing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  namespace: general-test
spec:
  rules:
  - host: foo.example.com
    http:
      paths:
      - path: /svc
        backend:
          serviceName: nginx-svc
          servicePort: 80
