---
apiVersion: v1
kind: Service
metadata:
  name: es
  labels:
    app: es
spec:
  ports:
    ## 对客户端提供服务的端口
    - port: 9200
      name: client
      targetPort: 9200
    ## 集群内与其他节点交互的端口
    - port: 9300
      name: node
      targetPort: 9300
  selector:
    ## 注意: service 的 selector 需要指定的是 
    ## Deployment -> spec -> template -> labels,
    ## 而不是 Deployment -> metadata -> lables.
    ## 可以说, Service与Deployment最终指向的目标都是Pod资源.
    app: es

---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  ports:
    - port: 5601
      name: webui
      targetPort: 5601
      nodePort: 30601
  selector:
    ## 注意: service 的 selector 需要指定的是 
    ## Deployment -> spec -> template -> labels,
    ## 而不是 Deployment -> metadata -> lables.
    ## 可以说, Service与Deployment最终指向的目标都是Pod资源.
    app: kibana
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
    - port: 8080
      name: nginx
      targetPort: 8080
      nodePort: 31080
  selector:
    ## 注意: service 的 selector 需要指定的是 
    ## Deployment -> spec -> template -> labels,
    ## 而不是 Deployment -> metadata -> lables.
    ## 可以说, Service与Deployment最终指向的目标都是Pod资源.
    app: nginx
  type: NodePort
