---
apiVersion: apps/v1
kind: Deployment
metadata:
  ## deploy 生成的 pod 的名称也是 es-xxx
  name: es
  labels:
    app: es
spec:
  replicas: 1
  selector:
    matchLabels:
      ## 这里的 label 是与下面的 template -> metadata -> label 匹配的,
      ## 表示一种管理关系
      app: es
  template:
    metadata:
      labels:
        app: es
    spec:
      initContainers:
        ## elasticsearch 会对配置文件目录进行写入操作, 而通过 configmap 挂载的目录是只读的,
        ## es 在写入时会导致异常退出, 这里用一个 initContainers 做一个拷贝工作.
        - name: config
          image: busybox
          ## 注意: 这里用超级权限修改容器内部的 sysctl 内核参数, 会同时影响宿主机本身的参数.
          command: 
            - sysctl
            - -w
            - vm.max_map_count=655300
          securityContext:
            privileged: true
      containers:
        - name: es
          image: elasticsearch:7.2.0
          imagePullPolicy: IfNotPresent
          env: 
            ## jvm 参数在一个独立的配置文件 jvm.options 中.
            - name: ES_JAVA_OPTS
              value: "-Xmx1g -Xms1g"
            ## es配置文件中的所有键应该都可以在 env 中直接设置, 比如
            ## name: xpack.security.enabled
            ## value: 'true'
            ## 但是, username/password 这两个参数我找了很多地方, 没有找到在配置文件中的键名.
            ## 所有文章都是通过环境变量来设置的.
            ## 貌似这些环境变量(包括上面的 java opts), 都在 es 内部被通过 ${ES_XXX} 进行了替换,
            ## 即, 这些环境的优先级很高.
            - name: ELASTIC_USERNAME
              value: "elastic"
            - name: ELASTIC_PASSWORD
              value: "123456"
          volumeMounts:
            - name: es-config-vol
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              ## subPath 的意思是, 该 configmap 并不影响整个目录, 只影响 elasticsearch.yml 这一文件.
              subPath: elasticsearch.yml
      volumes:
        - name: es-config-vol
          configMap:
            name: es-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  ## deploy 生成的 pod 的名称也是 kibana-xxx
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      ## 这里的 label 是与下面的 template -> metadata -> label 匹配的,
      ## 表示一种管理关系
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: kibana:7.2.0
          imagePullPolicy: IfNotPresent
          env: 
            ## 这里的 es 指的是 service 名称
            - name: ELASTICSEARCH_HOSTS
              value: http://es:9200
            ## 其实 username 和 password 在配置文件或是环境变量中定义都可以,
            ## 但是貌似使用环境变量的时候, 密码不能定义为 123456, 哪怕已经用双引号包裹.
            ## 所以这里把这两个 key 注释掉, 写在了配置文件里...
            ## - name: ELASTICSEARCH_USERNAME
            ##   value: "elastic"
            ## - name: ELASTICSEARCH_PASSWORD
            ##   value: "123456"
          volumeMounts:
            - name: kibana-config-vol
              mountPath: /usr/share/kibana/config/kibana.yml
              subPath: kibana.yml
      volumes:
        - name: kibana-config-vol
          configMap:
            name: kibana-config
