/*
   哇咔咔, 我是文件头!!!
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "mycrd/pkg/client/clientset/versioned/typed/mycrdgroup/v1"

	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeMycrdgroupV1 struct {
	*testing.Fake
}

func (c *FakeMycrdgroupV1) MyCrds(namespace string) v1.MyCrdInterface {
	return &FakeMyCrds{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeMycrdgroupV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
