---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  ## deploy 生成的 pod 的名称也是 logstash-xxx
  name: logstash
  labels:
    app: logstash
spec:
  selector:
    matchLabels:
      ## 这里的 label 是与下面的 template -> metadata -> label 匹配的,
      ## 表示一种管理关系
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: logstash:7.2.0
          imagePullPolicy: IfNotPresent
          env: 
            - name: LS_JAVA_OPTS
              value: "-Xmx256m -Xms256m"
          volumeMounts:
            - name: logstash-config-vol
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml
            - name: logstash-pipeline-config-vol
              mountPath: /usr/share/logstash/pipeline
            - name: nginx-log-vol
              mountPath: /var/log/nginx
      volumes:
        - name: logstash-config-vol
          configMap:
            name: logstash-config
        - name: logstash-pipeline-config-vol
          configMap:
            name: logstash-pipeline-config
        - name: nginx-log-vol
          hostPath:
            path: /var/log/kuber-nginx

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  ## deploy 生成的 pod 的名称也是 nginx-xxx
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      ## 这里的 label 是与下面的 template -> metadata -> label 匹配的,
      ## 表示一种管理关系
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        ## 官方镜像直接将日志打印到标准输出.
        ## 我们希望将日志输出到文件中, 由 logstash 完成采集.
        - name: nginx
          image: registry.cn-hangzhou.aliyuncs.com/generals-space/centos7
          command: ["tail", "-f", "/etc/os-release"]
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: nginx-config-vol
              mountPath: /etc/nginx/conf.d
            - name: nginx-log-vol
              mountPath: /var/log/nginx
      volumes:
        - name: nginx-config-vol
          configMap:
            name: nginx-config
        - name: nginx-log-vol
          hostPath:
            path: /var/log/kuber-nginx
