/*
   哇咔咔, 我是文件头!!!
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "mycrd/pkg/apis/mycrdgroup/v1"
	"mycrd/pkg/client/clientset/versioned/scheme"

	rest "k8s.io/client-go/rest"
)

type MycrdgroupV1Interface interface {
	RESTClient() rest.Interface
	MyCrdsGetter
}

// MycrdgroupV1Client is used to interact with features provided by the mycrdgroup.k8s.io group.
type MycrdgroupV1Client struct {
	restClient rest.Interface
}

func (c *MycrdgroupV1Client) MyCrds(namespace string) MyCrdInterface {
	return newMyCrds(c, namespace)
}

// NewForConfig creates a new MycrdgroupV1Client for the given config.
func NewForConfig(c *rest.Config) (*MycrdgroupV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &MycrdgroupV1Client{client}, nil
}

// NewForConfigOrDie creates a new MycrdgroupV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *MycrdgroupV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new MycrdgroupV1Client for the given RESTClient.
func New(c rest.Interface) *MycrdgroupV1Client {
	return &MycrdgroupV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *MycrdgroupV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
