apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: alicloud-disk-ssd-hangzhou-g
provisioner: diskplugin.csi.alibabacloud.com
parameters:
    ## 这里要按照集群所在区域填写
    zoneId: cn-hangzhou-g
    regionId: cn-hangzhou
    type: cloud_ssd
reclaimPolicy: Retain
