---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path
provisioner: rancher.io/local-path
## `WaitForFirstConsumer`: 单纯创建pvc时不会自动创建pv, 也不会创建实际目录, 此时pvc的状态保持为`Pending`. 
## 只有当pod引用此pvc时才会创建, 同时pvc的状态会变为`Bound`. 不过pod被删除后, 遗留的pvc仍然为`Bound`状态.
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
